// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icfrpyzoaixyblpxqnci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZnJweXpvYWl4eWJscHhxbmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDA5NTgsImV4cCI6MjA2NjUxNjk1OH0.z0-U1kHy5Cp-2x-RXDPFRkt9hYUaS8eAkhXeDMa6UCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);